site:
  title: Celestial_Navigation_pi Manual
  url:  https://nowhere.net
  start_page: celestial_navigation:ROOT:celestial_navigation.adoc
content:
  sources:
    - url: ../
      start_path: manual/celestial_navigation/
      branches: HEAD
      edit_url: true
ui:   
  bundle:
    url: https://gitlab.com/leamas/antora-ui-default/-/raw/master/latest/ui-bundle.zip
    snapshot: true
output:
  dir: ./docs
  clean: true              